# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    resource_group_name  = "dummy-rg"
    storage_account_name = "nabkavopstfstate"
    container_name       = "nabkavopstfstatecont"
    key                  = "./terraform.tfstate"
    access_key           = ""
    subscription_id      = "b7d84abb-da82-415d-801b-d0b26c0f9548"
  }
}
